
import type { AiTool, AiToolCategory } from '@/types';

export const aiToolCategories: AiToolCategory[] = [
  'LLM',
  'Photo',
  'Video',
  'Coding',
  'Audio',
  'Productivity',
  'Design',
  'Other',
];

// Helper function to create a slug from a name
export const createSlug = (name: string) => {
  return name
    .toLowerCase()
    .replace(/\./g, '-') // Replace dots with hyphens
    .replace(/\s+/g, '-') // Replace whitespace with hyphens
    .replace(/[^\w-]+/g, '') // Remove special characters except word characters and hyphens
    .replace(/--+/g, '-') // Replace multiple hyphens with single hyphen
    .replace(/^-+|-+$/g, '') // Trim leading/trailing hyphens
    .trim();
};

export const aiTools: AiTool[] = [
  {
    id: '1',
    name: 'GPT-4 Turbo',
    description: 'Advanced large language model for text generation and understanding.',
    longDescription: 'GPT-4 Turbo by OpenAI is a state-of-the-art language model with a larger context window and more up-to-date knowledge, excelling in complex reasoning, coding, and creative text generation.',
    category: 'LLM',
    website: 'https://openai.com/gpt-4',
    imageUrl: `/ai-tools/${createSlug('GPT-4 Turbo')}.png`,
    imageKeywords: 'GPT-4 logo',
    rating: 4.9,
    tags: ['text generation', 'nlp', 'coding assistant'],
    pricing: 'Paid',
    features: ['128k context window', 'Vision capabilities', 'Advanced reasoning'],
  },
  {
    id: '2',
    name: 'Midjourney',
    description: 'AI image generator creating stunning visuals from text prompts.',
    longDescription: 'Midjourney is an independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species. It generates images from textual descriptions, known as "prompts".',
    category: 'Photo',
    website: 'https://www.midjourney.com',
    imageUrl: `/ai-tools/${createSlug('Midjourney')}.png`,
    imageKeywords: 'Midjourney art',
    rating: 4.8,
    tags: ['image generation', 'art', 'design'],
    pricing: 'Paid',
    features: ['High-quality artistic images', 'Discord-based interface', 'Community showcase'],
  },
  {
    id: '3',
    name: 'Runway Gen-2',
    description: 'Generate novel videos with text, images or video clips.',
    longDescription: 'Runway Gen-2 is a multimodal AI system that can generate novel videos with text, images or video clips. It allows users to create video content in various styles and moods.',
    category: 'Video',
    website: 'https://runwayml.com',
    imageUrl: `/ai-tools/${createSlug('Runway Gen-2')}.png`,
    imageKeywords: 'RunwayML video',
    rating: 4.7,
    tags: ['video generation', 'text-to-video', 'creative tool'],
    pricing: 'Freemium',
    features: ['Text-to-video', 'Image-to-video', 'Video stylization', 'Inpainting'],
  },
  {
    id: '4',
    name: 'GitHub Copilot',
    description: 'AI pair programmer that helps you write code faster.',
    longDescription: 'GitHub Copilot is an AI pair programmer that offers autocomplete-style suggestions as you code. You can get suggestions from GitHub Copilot either by starting to write the code you want to use, or by writing a natural language comment describing what you want the code to do.',
    category: 'Coding',
    website: 'https://copilot.github.com',
    imageUrl: `/ai-tools/${createSlug('GitHub Copilot')}.png`,
    imageKeywords: 'Copilot logo',
    rating: 4.6,
    tags: ['code assistant', 'developer tool', 'ide plugin'],
    pricing: 'Paid',
    features: ['Code suggestions', 'Natural language to code', 'Supports multiple languages', 'IDE integration'],
  },
  {
    id: '5',
    name: 'Descript',
    description: 'All-in-one audio and video editing, as easy as a doc.',
    longDescription: 'Descript is an AI-powered audio and video editing tool that transcribes audio to text, allowing users to edit media by editing the text. It offers features like overdub, screen recording, and podcasting tools.',
    category: 'Audio',
    website: 'https://www.descript.com',
    imageUrl: `/ai-tools/${createSlug('Descript')}.png`,
    imageKeywords: 'Descript audio',
    rating: 4.5,
    tags: ['audio editing', 'video editing', 'transcription', 'podcasting'],
    pricing: 'Freemium',
    features: ['AI transcription', 'Overdub (voice cloning)', 'Screen recording', 'Podcast production tools'],
  },
  {
    id: '6',
    name: 'Notion AI',
    description: 'AI-powered assistant integrated into your Notion workspace.',
    longDescription: 'Notion AI helps you work faster, write better, and think bigger, right in your Notion workspace. It can summarize documents, draft emails, translate text, and more.',
    category: 'Productivity',
    website: 'https://www.notion.so/ai',
    imageUrl: `/ai-tools/${createSlug('Notion AI')}.png`,
    imageKeywords: 'Notion AI',
    rating: 4.4,
    tags: ['writing assistant', 'summarization', 'workspace tool'],
    pricing: 'Freemium',
    features: ['Text generation & editing', 'Summarization', 'Action items extraction', 'Translation'],
  },
  {
    id: '7',
    name: 'Figma AI',
    description: 'AI tools to supercharge your design workflow in Figma.',
    longDescription: 'Figma AI integrates generative AI capabilities directly into the Figma design platform, helping designers automate tasks, generate design ideas, and iterate faster.',
    category: 'Design',
    website: 'https://www.figma.com/ai',
    imageUrl: `/ai-tools/${createSlug('Figma AI')}.png`,
    imageKeywords: 'Figma AI',
    rating: 4.3,
    tags: ['design tool', 'ui/ux', 'prototyping'],
    pricing: 'Paid',
    features: ['Generative design', 'Automated layout suggestions', 'Content generation for mockups'],
  },
  {
    id: '8',
    name: 'Claude 3 (Opus, Sonnet, Haiku)',
    description: 'A family of foundation models for various text-based tasks.',
    longDescription: 'Claude 3 by Anthropic offers a new generation of AI models (Haiku, Sonnet, Opus) that balance intelligence, speed, and cost, suitable for a wide range of applications from quick summarization to complex analysis.',
    category: 'LLM',
    website: 'https://www.anthropic.com/claude',
    imageUrl: `/ai-tools/${createSlug('Claude 3 (Opus, Sonnet, Haiku)')}.png`,
    imageKeywords: 'Claude AI',
    rating: 4.8,
    tags: ['llm', 'text analysis', 'chatbot'],
    pricing: 'Freemium',
    features: ['Multiple model sizes', 'Strong safety features', 'Long context processing', 'Vision capabilities'],
  },
  {
    id: '9',
    name: 'Adobe Firefly',
    description: 'Generative AI for creative expression integrated into Adobe products.',
    longDescription: 'Adobe Firefly is a family of creative generative AI models coming to Adobe products. It focuses on generating images and text effects designed to be safe for commercial use.',
    category: 'Photo',
    website: 'https://www.adobe.com/sensei/generative-ai/firefly.html',
    imageUrl: `/ai-tools/${createSlug('Adobe Firefly')}.png`,
    imageKeywords: 'Adobe Firefly',
    rating: 4.7,
    tags: ['image generation', 'text effects', 'adobe suite'],
    pricing: 'Freemium',
    features: ['Ethically sourced training data', 'Integration with Photoshop, Illustrator', 'Text-to-image', 'Generative fill'],
  },
  {
    id: '10',
    name: 'Synthesia',
    description: 'Create AI videos by typing in text. No actors, cameras or mics needed.',
    longDescription: 'Synthesia is an AI video generation platform that allows users to create professional-looking videos with AI avatars and voiceovers in multiple languages, simply by typing text.',
    category: 'Video',
    website: 'https://www.synthesia.io',
    imageUrl: `/ai-tools/${createSlug('Synthesia')}.png`,
    imageKeywords: 'Synthesia video',
    rating: 4.6,
    tags: ['ai video', 'avatar', 'text-to-speech'],
    pricing: 'Paid',
    features: ['AI avatars', 'Multi-language support', 'Customizable templates', 'Screen recording'],
  },
  {
    id: '11',
    name: 'Llama 3',
    description: 'Open-source large language model from Meta AI, known for its performance and accessibility.',
    longDescription: 'Llama 3 by Meta AI is a powerful open-source LLM designed for a variety of natural language processing tasks. It comes in different sizes, offering a balance between performance and computational resources.',
    category: 'LLM',
    website: 'https://ai.meta.com/llama/',
    imageUrl: `/ai-tools/${createSlug('Llama 3')}.png`,
    imageKeywords: 'Llama3 Meta',
    rating: 4.7,
    tags: ['open source', 'llm', 'research'],
    pricing: 'Free',
    features: ['Multiple model sizes (8B, 70B)', 'Improved reasoning', 'Commercially permissive license'],
  },
  {
    id: '12',
    name: 'Gemini Advanced (1.5 Pro)',
    description: 'Google\'s most capable AI model, integrated into Gemini Advanced for complex tasks.',
    longDescription: 'Gemini 1.5 Pro, powering Gemini Advanced, is Google\'s next-generation multimodal model. It excels in understanding and generating text, code, images, and more, with a very large context window.',
    category: 'LLM',
    website: 'https://gemini.google.com/advanced',
    imageUrl: `/ai-tools/${createSlug('Gemini Advanced (1.5 Pro)')}.png`,
    imageKeywords: 'Gemini Advanced',
    rating: 4.8,
    tags: ['multimodal', 'google ai', 'large context'],
    pricing: 'Paid',
    features: ['1 million token context window', 'Advanced reasoning and coding', 'Multimodal understanding'],
  },
  {
    id: '13',
    name: 'Cohere Command R+',
    description: 'Enterprise-grade LLM optimized for real-world business applications.',
    longDescription: 'Cohere\'s Command R+ is a highly performant LLM designed for enterprise use cases, focusing on scalability, reliability, and data privacy for tasks like RAG and tool use.',
    category: 'LLM',
    website: 'https://cohere.com/models/command-r-plus',
    imageUrl: `/ai-tools/${createSlug('Cohere Command R+')}.png`,
    imageKeywords: 'Cohere AI',
    rating: 4.6,
    tags: ['enterprise', 'rag', 'tool use'],
    pricing: 'Paid',
    features: ['Optimized for RAG', 'Multilingual capabilities', 'Strong tool use functionality', 'Data privacy focus'],
  },
  {
    id: '14',
    name: 'AI21 Jurassic-2',
    description: 'Family of large language models from AI21 Labs for various text generation needs.',
    longDescription: 'AI21 Labs\' Jurassic-2 models provide powerful text generation capabilities, offering different model sizes to suit various application requirements, from creative writing to summarization.',
    category: 'LLM',
    website: 'https://www.ai21.com/studio',
    imageUrl: `/ai-tools/${createSlug('AI21 Jurassic-2')}.png`,
    imageKeywords: 'AI21 Labs',
    rating: 4.5,
    tags: ['text generation', 'nlp api', 'custom models'],
    pricing: 'Paid',
    features: ['Multiple model sizes', 'Fine-tuning options', 'Task-specific APIs'],
  },
  {
    id: '15',
    name: 'Perplexity AI',
    description: 'Conversational AI-powered search engine providing direct answers with sources.',
    longDescription: 'Perplexity AI redefines search by providing direct, cited answers to user queries using LLMs. It aims to be an "answer engine" rather than just a list of links.',
    category: 'LLM',
    website: 'https://www.perplexity.ai',
    imageUrl: `/ai-tools/${createSlug('Perplexity AI')}.png`,
    imageKeywords: 'Perplexity search',
    rating: 4.7,
    tags: ['search engine', 'answer engine', 'research'],
    pricing: 'Freemium',
    features: ['Cited sources', 'Conversational follow-ups', 'Focus modes for different types of search'],
  },
  {
    id: '16',
    name: 'Writesonic / Chatsonic',
    description: 'AI writing assistant for creating SEO-friendly marketing copy, articles, and more.',
    longDescription: 'Writesonic is an AI writing tool that helps generate various forms of content, from blog posts and ads to product descriptions. Chatsonic is its conversational AI component, similar to ChatGPT but with Google search integration.',
    category: 'LLM',
    website: 'https://writesonic.com',
    imageUrl: `/ai-tools/${createSlug('Writesonic / Chatsonic')}.png`,
    imageKeywords: 'Writesonic AI',
    rating: 4.4,
    tags: ['content creation', 'seo', 'marketing'],
    pricing: 'Freemium',
    features: ['Wide range of templates', 'Chatsonic for real-time data', 'Image generation capabilities'],
  },
  {
    id: '17',
    name: 'Jasper',
    description: 'AI content platform for creating high-quality marketing copy and content at scale.',
    longDescription: 'Jasper is a popular AI writing assistant tailored for marketing teams and content creators, offering features to produce various types of copy, blog posts, social media updates, and more.',
    category: 'LLM',
    website: 'https://www.jasper.ai',
    imageUrl: `/ai-tools/${createSlug('Jasper')}.png`,
    imageKeywords: 'Jasper AI',
    rating: 4.5,
    tags: ['marketing copy', 'ai writer', 'content scaling'],
    pricing: 'Paid',
    features: ['Brand voice consistency', 'Collaboration tools', 'Extensive template library', 'SEO mode'],
  },
  {
    id: '18',
    name: 'Rytr',
    description: 'An AI writing assistant that helps you create high-quality content in just a few seconds.',
    longDescription: 'Rytr provides a simple and affordable AI writing solution for generating various content types, including emails, blog ideas, ad copy, and social media posts, supporting multiple languages and tones.',
    category: 'LLM',
    website: 'https://rytr.me',
    imageUrl: `/ai-tools/${createSlug('Rytr')}.png`,
    imageKeywords: 'Rytr writing',
    rating: 4.3,
    tags: ['copywriting', 'content generation', 'affordable'],
    pricing: 'Freemium',
    features: ['Multiple use cases & templates', 'Support for 30+ languages', 'Tone selection', 'Plagiarism checker'],
  },
   {
    id: '19',
    name: 'Grok',
    description: 'AI by xAI, designed to answer questions with a bit of wit and has real-time access to X (Twitter).',
    longDescription: 'Grok is an AI modeled after the Hitchhiker\'s Guide to the Galaxy, aiming to answer almost anything and, far harder, even suggest what questions to ask. It has real-time access to information via the X platform.',
    category: 'LLM',
    website: 'https://x.ai/grok',
    imageUrl: `/ai-tools/${createSlug('Grok')}.png`,
    imageKeywords: 'Grok xAI',
    rating: 4.5,
    tags: ['conversational ai', 'real-time info', 'twitter x'],
    pricing: 'Paid',
    features: ['Real-time X platform access', 'Witty and rebellious streak', 'Handles spicy questions'],
  },
  {
    id: '20',
    name: 'Mistral Large',
    description: 'Mistral AI\'s top-tier language model, offering high reasoning capabilities.',
    longDescription: 'Mistral Large is a flagship model from Mistral AI, delivering top-tier reasoning capacities for complex multilingual reasoning tasks, including text understanding, transformation, and code generation.',
    category: 'LLM',
    website: 'https://mistral.ai/news/mistral-large/',
    imageUrl: `/ai-tools/${createSlug('Mistral Large')}.png`,
    imageKeywords: 'Mistral AI',
    rating: 4.7,
    tags: ['reasoning', 'multilingual', 'api'],
    pricing: 'Paid',
    features: ['High reasoning capabilities', 'Native multilingual support', 'Code generation', 'Function calling'],
  },
  {
    id: '21',
    name: 'DALL-E 3',
    description: 'AI model by OpenAI that creates realistic images and art from a description in natural language.',
    longDescription: 'DALL-E 3, developed by OpenAI, can generate highly detailed and contextually relevant images from text prompts. It is integrated into ChatGPT Plus and the OpenAI API.',
    category: 'Photo',
    website: 'https://openai.com/dall-e-3',
    imageUrl: `/ai-tools/${createSlug('DALL-E 3')}.png`,
    imageKeywords: 'DALL-E image',
    rating: 4.8,
    tags: ['image generation', 'openai', 'art creation'],
    pricing: 'Paid',
    features: ['Integration with ChatGPT', 'High prompt adherence', 'Various artistic styles'],
  },
  {
    id: '22',
    name: 'Stable Diffusion XL',
    description: 'Powerful open-source image generation model by Stability AI.',
    longDescription: 'Stable Diffusion XL (SDXL) is an advanced open-source model from Stability AI, capable of generating high-resolution images with improved photorealism and composition compared to previous versions.',
    category: 'Photo',
    website: 'https://stability.ai/stablediffusion',
    imageUrl: `/ai-tools/${createSlug('Stable Diffusion XL')}.png`,
    imageKeywords: 'Stable Diffusion',
    rating: 4.7,
    tags: ['open source', 'image generation', 'high resolution'],
    pricing: 'Free',
    features: ['Open source and customizable', 'High resolution output', 'Active community support', 'Various UIs available'],
  },
  {
    id: '23',
    name: 'Leonardo.Ai',
    description: 'Platform for creating stunning game assets, concept art, and more with AI.',
    longDescription: 'Leonardo.Ai offers a suite of tools for generating visual assets using fine-tuned AI models. It\'s particularly popular for game development, concept art, and character design.',
    category: 'Photo',
    website: 'https://leonardo.ai',
    imageUrl: `/ai-tools/${createSlug('Leonardo.Ai')}.png`,
    imageKeywords: 'Leonardo AI',
    rating: 4.6,
    tags: ['game assets', 'concept art', 'fine-tuned models'],
    pricing: 'Freemium',
    features: ['Pre-trained and custom models', 'Image editing tools', 'Canvas for in/outpainting', 'Texture generation'],
  },
  {
    id: '24',
    name: 'Playground AI',
    description: 'Online AI image creator and editor with powerful features and social aspects.',
    longDescription: 'Playground AI is a web-based platform for creating and editing images using AI. It offers various models, robust editing tools, and a community for sharing and discovering creations.',
    category: 'Photo',
    website: 'https://playgroundai.com',
    imageUrl: `/ai-tools/${createSlug('Playground AI')}.png`,
    imageKeywords: 'Playground AI',
    rating: 4.5,
    tags: ['online editor', 'social image creation', 'multiple models'],
    pricing: 'Freemium',
    features: ['Multiple AI models (inc. SDXL)', 'Canvas editor', 'Image upscaling', 'Social feed'],
  },
  {
    id: '25',
    name: 'Artbreeder',
    description: 'Create and explore images by breeding them together and fine-tuning genes.',
    longDescription: 'Artbreeder uses generative adversarial networks (GANs) to allow users to create unique images by "breeding" existing images, adjusting various "genes" to control features like age, gender, and artistic style.',
    category: 'Photo',
    website: 'https://www.artbreeder.com',
    imageUrl: `/ai-tools/${createSlug('Artbreeder')}.png`,
    imageKeywords: 'Artbreeder GAN',
    rating: 4.4,
    tags: ['image breeding', 'gan', 'character design'],
    pricing: 'Freemium',
    features: ['Unique image generation method', 'Portrait, landscape, and character creators', 'Community sharing'],
  },
  {
    id: '26',
    name: 'NightCafe Creator',
    description: 'AI Art Generator app. Create amazing artworks using the power of Artificial Intelligence.',
    longDescription: 'NightCafe Creator provides access to multiple AI art generation methods, including text-to-image (Stable Diffusion, DALL-E 2 via API) and style transfer, with a focus on community and ease of use.',
    category: 'Photo',
    website: 'https://nightcafe.studio',
    imageUrl: `/ai-tools/${createSlug('NightCafe Creator')}.png`,
    imageKeywords: 'NightCafe art',
    rating: 4.3,
    tags: ['ai art', 'multiple algorithms', 'community platform'],
    pricing: 'Freemium',
    features: ['Multiple generation algorithms', 'Daily free credits', 'Print-on-demand options', 'Active community'],
  },
  {
    id: '27',
    name: 'Deep Dream Generator',
    description: 'Create inspiring visual content in a collaboration with our AI enabled tools.',
    longDescription: 'Deep Dream Generator offers tools for AI art generation, including "Deep Style" (style transfer), "Thin Style," and "Deep Dream" effects, allowing users to transform photos or create new art.',
    category: 'Photo',
    website: 'https://deepdreamgenerator.com',
    imageUrl: `/ai-tools/${createSlug('Deep Dream Generator')}.png`,
    imageKeywords: 'Deep Dream',
    rating: 4.2,
    tags: ['style transfer', 'psychedelic art', 'photo effects'],
    pricing: 'Freemium',
    features: ['Deep Style (neural style transfer)', 'Text 2 Dream (text-to-image)', 'Community gallery'],
  },
  {
    id: '28',
    name: 'Canva AI Image Generator',
    description: 'Generate unique images from text within the Canva design platform.',
    longDescription: 'Canva\'s AI Image Generator allows users to create custom images directly within their Canva designs by simply describing what they want. It leverages models like Stable Diffusion.',
    category: 'Photo',
    website: 'https://www.canva.com/ai-image-generator/',
    imageUrl: `/ai-tools/${createSlug('Canva AI Image Generator')}.png`,
    imageKeywords: 'Canva AI',
    rating: 4.5,
    tags: ['canva integration', 'design tool', 'easy to use'],
    pricing: 'Freemium',
    features: ['Integrated into Canva workflow', 'Multiple styles', 'Easy to use for non-designers'],
  },
  {
    id: '29',
    name: 'Fotor AI Image Generator',
    description: 'Create stunning AI-generated images from text prompts with Fotor.',
    longDescription: 'Fotor\'s AI Image Generator allows users to turn text descriptions into images across various styles like concept art, realistic photos, cartoons, and more, as part of its broader photo editing suite.',
    category: 'Photo',
    website: 'https://www.fotor.com/features/ai-image-generator/',
    imageUrl: `/ai-tools/${createSlug('Fotor AI Image Generator')}.png`,
    imageKeywords: 'Fotor image',
    rating: 4.3,
    tags: ['photo editor', 'text-to-image', 'multiple styles'],
    pricing: 'Freemium',
    features: ['Variety of art styles', 'Integrated with Fotor photo editor', 'Face generator', 'Photo to art'],
  },
  {
    id: '30',
    name: 'Pixelcut AI',
    description: 'AI-powered tools for e-commerce, including background removal and product photos.',
    longDescription: 'Pixelcut offers a suite of AI tools primarily focused on e-commerce imagery, such as background removal, AI product photography, image resizing, and magic eraser.',
    category: 'Photo',
    website: 'https://pixelcut.ai',
    imageUrl: `/ai-tools/${createSlug('Pixelcut AI')}.png`,
    imageKeywords: 'Pixelcut ecommerce',
    rating: 4.4,
    tags: ['ecommerce', 'background removal', 'product photography'],
    pricing: 'Freemium',
    features: ['Background remover', 'Magic eraser', 'AI Photoshoot', 'Batch editing'],
  },
  {
    id: '31',
    name: 'Pika Labs',
    description: 'AI video generator and editor that brings your creative ideas to life.',
    longDescription: 'Pika Labs offers a platform to generate and edit videos from text prompts or images, enabling users to create dynamic video content, animations, and apply various styles.',
    category: 'Video',
    website: 'https://pika.art',
    imageUrl: `/ai-tools/${createSlug('Pika Labs')}.png`,
    imageKeywords: 'Pika Labs',
    rating: 4.7,
    tags: ['text-to-video', 'image-to-video', 'video editing'],
    pricing: 'Freemium',
    features: ['Text/Image to video', 'Video modification (expand canvas, change elements)', 'Lip sync'],
  },
  {
    id: '32',
    name: 'HeyGen',
    description: 'AI video generation platform with customizable avatars and voice cloning.',
    longDescription: 'HeyGen allows users to create engaging videos with realistic AI avatars, voice cloning, and text-to-video capabilities, suitable for marketing, training, and communication.',
    category: 'Video',
    website: 'https://www.heygen.com',
    imageUrl: `/ai-tools/${createSlug('HeyGen')}.png`,
    imageKeywords: 'HeyGen avatar',
    rating: 4.6,
    tags: ['ai avatar', 'voice cloning', 'marketing video'],
    pricing: 'Paid',
    features: ['Customizable AI avatars', 'Voice cloning in multiple languages', 'Text-to-video', 'Templates'],
  },
  {
    id: '33',
    name: 'Pictory AI',
    description: 'AI video maker that automatically creates short, highly-shareable branded videos from long-form content.',
    longDescription: 'Pictory uses AI to transform long-form content like blog posts, scripts, or webinars into engaging, short videos suitable for social media and marketing, complete with stock footage and voiceovers.',
    category: 'Video',
    website: 'https://pictory.ai',
    imageUrl: `/ai-tools/${createSlug('Pictory AI')}.png`,
    imageKeywords: 'Pictory video',
    rating: 4.5,
    tags: ['content repurposing', 'social media video', 'automated video'],
    pricing: 'Paid',
    features: ['Script-to-video', 'Article-to-video', 'Automatic visual selection', 'AI voiceovers'],
  },
  {
    id: '34',
    name: 'InVideo AI',
    description: 'Online video editor and maker with AI-powered features for quick video creation.',
    longDescription: 'InVideo offers an online video editing platform with AI tools to help create professional videos quickly, including text-to-video, pre-made templates, and a stock media library.',
    category: 'Video',
    website: 'https://invideo.io',
    imageUrl: `/ai-tools/${createSlug('InVideo AI')}.png`,
    imageKeywords: 'InVideo editor',
    rating: 4.4,
    tags: ['online video editor', 'text-to-video', 'templates'],
    pricing: 'Freemium',
    features: ['Text-to-video', 'Extensive template library', 'Stock media integration', 'Collaboration tools'],
  },
  {
    id: '35',
    name: 'Lumen5',
    description: 'AI-powered video creation platform for businesses to produce engaging video content.',
    longDescription: 'Lumen5 transforms blog posts and articles into captivating videos using AI, helping businesses and marketers easily create video content for social media and content marketing.',
    category: 'Video',
    website: 'https://lumen5.com',
    imageUrl: `/ai-tools/${createSlug('Lumen5')}.png`,
    imageKeywords: 'Lumen5 video',
    rating: 4.3,
    tags: ['article-to-video', 'marketing video', 'content creation'],
    pricing: 'Paid',
    features: ['AI-assisted content transformation', 'Branding customization', 'Media library', 'Multiple video formats'],
  },
  {
    id: '36',
    name: 'Kapwing AI',
    description: 'Online video editing suite with AI-powered tools for faster and smarter editing.',
    longDescription: 'Kapwing is a collaborative online video editing platform that incorporates AI tools like Smart Cut (automatic silence removal), auto-subtitling, background removal, and text-to-speech.',
    category: 'Video',
    website: 'https://www.kapwing.com/ai',
    imageUrl: `/ai-tools/${createSlug('Kapwing AI')}.png`,
    imageKeywords: 'Kapwing editor',
    rating: 4.5,
    tags: ['online editor', 'ai tools', 'subtitles', 'collaboration'],
    pricing: 'Freemium',
    features: ['Smart Cut', 'Auto-subtitling', 'Background remover', 'Text-to-speech', 'Templates'],
  },
  {
    id: '37',
    name: 'Veed.io AI',
    description: 'Online video editing platform with a suite of AI tools for easy video creation.',
    longDescription: 'Veed.io offers a simple online video editor packed with AI features like automatic subtitles, text-to-speech, background noise removal, and eye contact correction.',
    category: 'Video',
    website: 'https://www.veed.io/tools/ai-video-editor',
    imageUrl: `/ai-tools/${createSlug('Veed.io AI')}.png`,
    imageKeywords: 'Veed.io video',
    rating: 4.4,
    tags: ['video editing', 'subtitles', 'text-to-speech', 'easy to use'],
    pricing: 'Freemium',
    features: ['Automatic subtitles', 'Text-to-speech', 'Background noise removal', 'Screen recorder', 'Eye contact correction'],
  },
  {
    id: '38',
    name: 'DeepBrain AI',
    description: 'Create AI-generated videos featuring hyperrealistic virtual humans.',
    longDescription: 'DeepBrain AI specializes in creating videos with AI avatars that can speak from scripts. It\'s used for corporate training, news broadcasting, and customer service applications.',
    category: 'Video',
    website: 'https://www.deepbrain.io',
    imageUrl: `/ai-tools/${createSlug('DeepBrain AI')}.png`,
    imageKeywords: 'DeepBrain avatar',
    rating: 4.5,
    tags: ['ai avatar', 'virtual humans', 'text-to-video'],
    pricing: 'Paid',
    features: ['Hyperrealistic AI avatars', 'Text-to-speech with emotion', 'Custom avatar creation', 'API access'],
  },
  {
    id: '39',
    name: 'Hour One',
    description: 'AI video maker that turns text into presenter-led videos in minutes.',
    longDescription: 'Hour One enables businesses to create professional presenter-led videos at scale by transforming text into video content featuring virtual human presenters.',
    category: 'Video',
    website: 'https://hourone.ai',
    imageUrl: `/ai-tools/${createSlug('Hour One')}.png`,
    imageKeywords: 'Hour One',
    rating: 4.3,
    tags: ['ai presenter', 'corporate video', 'scalable video'],
    pricing: 'Paid',
    features: ['Virtual presenters', 'Multilingual support', 'API for automation', 'Customizable backgrounds and branding'],
  },
  {
    id: '40',
    name: 'D-ID',
    description: 'AI platform to generate videos of photorealistic avatars from text or audio.',
    longDescription: 'D-ID uses generative AI to create videos featuring talking avatars from a single photo, combined with text or audio input. It is used for creative content, marketing, and personalized communication.',
    category: 'Video',
    website: 'https://www.d-id.com',
    imageUrl: `/ai-tools/${createSlug('D-ID')}.png`,
    imageKeywords: 'D-ID avatar',
    rating: 4.4,
    tags: ['talking avatars', 'photo-to-video', 'creative ai'],
    pricing: 'Freemium',
    features: ['Photo-to-talking-avatar', 'Text or audio input', 'API available', 'Realistic lip-sync'],
  },
  {
    id: '41',
    name: 'Tabnine',
    description: 'AI assistant for software developers, providing code completion in your IDE.',
    longDescription: 'Tabnine is an AI code completion tool that learns from your code and publicly available code to suggest relevant completions, helping developers write code faster and with fewer errors.',
    category: 'Coding',
    website: 'https://www.tabnine.com',
    imageUrl: `/ai-tools/${createSlug('Tabnine')}.png`,
    imageKeywords: 'Tabnine code',
    rating: 4.5,
    tags: ['code completion', 'ide plugin', 'developer productivity'],
    pricing: 'Freemium',
    features: ['Whole-line and full-function code completions', 'Supports many languages', 'Local and cloud models', 'Team learning options'],
  },
  {
    id: '42',
    name: 'Amazon CodeWhisperer',
    description: 'AI coding companion from AWS, providing real-time code suggestions.',
    longDescription: 'Amazon CodeWhisperer is an AI coding assistant that generates code recommendations in real time based on developers’ comments in natural language and prior code in their IDE.',
    category: 'Coding',
    website: 'https://aws.amazon.com/codewhisperer/',
    imageUrl: `/ai-tools/${createSlug('Amazon CodeWhisperer')}.png`,
    imageKeywords: 'CodeWhisperer AWS',
    rating: 4.4,
    tags: ['aws', 'code generation', 'ide integration'],
    pricing: 'Free',
    features: ['Real-time code suggestions', 'Security scans for generated code', 'Reference tracker for open source', 'Optimized for AWS services'],
  },
  {
    id: '43',
    name: 'Replit GhostWriter',
    description: 'AI coding assistant integrated into the Replit online IDE.',
    longDescription: 'Replit GhostWriter provides AI-powered features like code completion, code explanation, and bug fixing directly within the Replit collaborative browser-based IDE.',
    category: 'Coding',
    website: 'https://replit.com/ghostwriter',
    imageUrl: `/ai-tools/${createSlug('Replit GhostWriter')}.png`,
    imageKeywords: 'Replit AI',
    rating: 4.3,
    tags: ['online ide', 'ai pair programmer', 'code explanation'],
    pricing: 'Paid',
    features: ['Context-aware code completion', 'Explain code functionality', 'Generate code from prompts', 'Transform and debug code'],
  },
  {
    id: '44',
    name: 'Codeium',
    description: 'Free AI-powered toolkit for developers, offering autocomplete and search.',
    longDescription: 'Codeium provides AI-based code completion and natural language search capabilities for codebases, aiming to accelerate software development. It supports a wide range of IDEs and languages.',
    category: 'Coding',
    website: 'https://codeium.com',
    imageUrl: `/ai-tools/${createSlug('Codeium')}.png`,
    imageKeywords: 'Codeium free',
    rating: 4.6,
    tags: ['free ai coding', 'code completion', 'code search'],
    pricing: 'Free',
    features: ['Unlimited code completions', 'IDE integration for popular editors', 'Natural language code search', 'Individual and enterprise options'],
  },
  {
    id: '45',
    name: 'Sourcegraph Cody',
    description: 'AI coding assistant that understands your entire codebase.',
    longDescription: 'Cody by Sourcegraph is an AI coding assistant that uses your codebase context to provide accurate code generation, explanations, and answers to questions about your code.',
    category: 'Coding',
    website: 'https://sourcegraph.com/cody',
    imageUrl: `/ai-tools/${createSlug('Sourcegraph Cody')}.png`,
    imageKeywords: 'Sourcegraph Cody',
    rating: 4.5,
    tags: ['codebase context', 'ai assistant', 'enterprise coding'],
    pricing: 'Freemium',
    features: ['Understands full codebase context', 'Code generation and autocompletion', 'Explain code', 'Fix bugs', 'Integrates with Sourcegraph search'],
  },
  {
    id: '46',
    name: 'AskCodi',
    description: 'AI coding assistant with a suite of tools for developers.',
    longDescription: 'AskCodi provides various AI-powered functionalities such as code generation from natural language, code explanation, test case generation, and documentation writing, supporting multiple languages.',
    category: 'Coding',
    website: 'https://www.askcodi.com',
    imageUrl: `/ai-tools/${createSlug('AskCodi')}.png`,
    imageKeywords: 'AskCodi dev',
    rating: 4.2,
    tags: ['code generation', 'test generation', 'documentation'],
    pricing: 'Freemium',
    features: ['Code generation', 'Code explanation', 'Test case writing', 'Documentation', 'IDE extensions'],
  },
  {
    id: '47',
    name: 'Mutable.ai',
    description: 'AI-accelerated software development, focusing on code transformation and generation.',
    longDescription: 'Mutable.ai offers AI tools to help refactor, document, and test code, aiming to improve code quality and development speed through AI-driven transformations and suggestions.',
    category: 'Coding',
    website: 'https://mutable.ai',
    imageUrl: `/ai-tools/${createSlug('Mutable.ai')}.png`,
    imageKeywords: 'MutableAI refactor',
    rating: 4.3,
    tags: ['code refactoring', 'ai software development', 'code quality'],
    pricing: 'Paid',
    features: ['AI-powered code refactoring', 'Automated test generation', 'Code documentation', 'VS Code extension'],
  },
  {
    id: '48',
    name: 'Blackbox AI',
    description: 'AI coding assistant that helps you code faster by finding code snippets and generating code.',
    longDescription: 'Blackbox AI allows developers to search for code snippets using natural language and provides AI-powered code generation and completion features to speed up the development process.',
    category: 'Coding',
    website: 'https://www.useblackbox.io',
    imageUrl: `/ai-tools/${createSlug('Blackbox AI')}.png`,
    imageKeywords: 'Blackbox code',
    rating: 4.1,
    tags: ['code search', 'snippet finder', 'code generation'],
    pricing: 'Freemium',
    features: ['Natural language code search', 'Code generation', 'IDE integration', 'Track coding history'],
  },
  {
    id: '49',
    name: 'Phind',
    description: 'AI search engine for developers, providing instant answers and code examples.',
    longDescription: 'Phind is an AI search engine tailored for developers. It understands technical questions and provides answers with code examples, explanations, and links to relevant documentation.',
    category: 'Coding',
    website: 'https://www.phind.com',
    imageUrl: `/ai-tools/${createSlug('Phind')}.png`,
    imageKeywords: 'Phind search',
    rating: 4.6,
    tags: ['developer search', 'ai answers', 'code examples'],
    pricing: 'Free',
    features: ['Technical question answering', 'Code generation', 'Links to sources', 'Pair programming mode'],
  },
  {
    id: '50',
    name: 'Bito AI',
    description: 'AI assistant that helps developers generate code, explain concepts, and write tests.',
    longDescription: 'Bito AI is designed to make developers 10x faster with features like code generation, code explanation, comment generation, test case creation, and performance checking.',
    category: 'Coding',
    website: 'https://bito.ai',
    imageUrl: `/ai-tools/${createSlug('Bito AI')}.png`,
    imageKeywords: 'Bito dev',
    rating: 4.4,
    tags: ['developer productivity', 'code generation', 'test creation', 'explain code'],
    pricing: 'Freemium',
    features: ['Generate code', 'Explain code & concepts', 'Generate unit tests', 'Create comments', 'Check performance'],
  },
  {
    id: '51',
    name: 'ElevenLabs',
    description: 'AI voice generator for lifelike text-to-speech and voice cloning.',
    longDescription: 'ElevenLabs provides advanced AI-powered text-to-speech and voice cloning technology, enabling creators to generate realistic and expressive audio content in various languages and voices.',
    category: 'Audio',
    website: 'https://elevenlabs.io',
    imageUrl: `/ai-tools/${createSlug('ElevenLabs')}.png`,
    imageKeywords: 'ElevenLabs voice',
    rating: 4.8,
    tags: ['text-to-speech', 'voice cloning', 'ai voice'],
    pricing: 'Freemium',
    features: ['Realistic voice generation', 'Voice cloning from short samples', 'Multilingual support', 'Fine-grained voice control'],
  },
  {
    id: '52',
    name: 'Murf.ai',
    description: 'Versatile AI voice generator for creating studio-quality voiceovers.',
    longDescription: 'Murf.ai offers a wide range of AI voices for creating professional voiceovers for videos, presentations, podcasts, and e-learning content, with options to customize pitch, tone, and speed.',
    category: 'Audio',
    website: 'https://murf.ai',
    imageUrl: `/ai-tools/${createSlug('Murf.ai')}.png`,
    imageKeywords: 'MurfAI voiceover',
    rating: 4.6,
    tags: ['voiceover', 'ai narrator', 'e-learning audio'],
    pricing: 'Freemium',
    features: ['Large library of AI voices', 'Voice customization', 'Integration with video tools', 'Team collaboration'],
  },
  {
    id: '53',
    name: 'AIVA',
    description: 'AI music generation assistant for creating original compositions.',
    longDescription: 'AIVA (Artificial Intelligence Virtual Artist) is an AI that composes emotional soundtrack music for films, games, commercials, and other media, offering various styles and moods.',
    category: 'Audio',
    website: 'https://www.aiva.ai',
    imageUrl: `/ai-tools/${createSlug('AIVA')}.png`,
    imageKeywords: 'AIVA music',
    rating: 4.4,
    tags: ['music generation', 'soundtrack', 'ai composer'],
    pricing: 'Freemium',
    features: ['Generates music in various styles', 'User-influenced compositions', 'Royalty-free options', 'MIDI export'],
  },
  {
    id: '54',
    name: 'Amper Music',
    description: 'AI music composition tools for content creators (Acquired by Shutterstock).',
    longDescription: 'Amper Music (now part of Shutterstock) provides AI tools to create custom, royalty-free music tracks quickly by specifying mood, style, and length, catering to video producers and content creators.',
    category: 'Audio',
    website: 'https://www.shutterstock.com/discover/amper-music',
    imageUrl: `/ai-tools/${createSlug('Amper Music')}.png`,
    imageKeywords: 'Amper music',
    rating: 4.2,
    tags: ['royalty-free music', 'ai music', 'video soundtrack'],
    pricing: 'Paid',
    features: ['Custom track creation', 'Integration with Shutterstock library', 'Mood and genre selection'],
  },
  {
    id: '55',
    name: 'Adobe Podcast (Enhance Speech)',
    description: 'AI-powered audio recording and editing, with a focus on speech enhancement.',
    longDescription: 'Adobe Podcast offers web-based tools for recording and editing audio, featuring an "Enhance Speech" function that uses AI to remove noise and improve the clarity of voice recordings, making them sound professional.',
    category: 'Audio',
    website: 'https://podcast.adobe.com',
    imageUrl: `/ai-tools/${createSlug('Adobe Podcast (Enhance Speech)')}.png`,
    imageKeywords: 'Adobe Podcast',
    rating: 4.7,
    tags: ['speech enhancement', 'noise reduction', 'podcast tool'],
    pricing: 'Free',
    features: ['AI-powered speech enhancement', 'Web-based recording and editing', 'Mic check feature'],
  },
  {
    id: '56',
    name: 'Krisp.ai',
    description: 'AI-powered noise cancelling app for clear calls and recordings.',
    longDescription: 'Krisp uses AI to remove background noise and echo from your calls and recordings in real-time, ensuring clear communication across various apps like Zoom, Teams, and Discord.',
    category: 'Audio',
    website: 'https://krisp.ai',
    imageUrl: `/ai-tools/${createSlug('Krisp.ai')}.png`,
    imageKeywords: 'Krisp noise',
    rating: 4.5,
    tags: ['noise cancellation', 'clear calls', 'productivity audio'],
    pricing: 'Freemium',
    features: ['Real-time noise removal', 'Echo cancellation', 'Works with most communication apps', 'Voice clarity improvement'],
  },
  {
    id: '57',
    name: 'Otter.ai',
    description: 'AI meeting assistant that records audio, writes notes, and generates summaries.',
    longDescription: 'Otter.ai provides real-time transcription for meetings and interviews, identifies speakers, and generates summaries, helping teams stay organized and productive.',
    category: 'Audio',
    website: 'https://otter.ai',
    imageUrl: `/ai-tools/${createSlug('Otter.ai')}.png`,
    imageKeywords: 'OtterAI notes',
    rating: 4.6,
    tags: ['transcription', 'meeting notes', 'ai assistant'],
    pricing: 'Freemium',
    features: ['Real-time transcription', 'Speaker identification', 'Automated meeting summaries', 'Integration with Zoom, Google Meet'],
  },
  {
    id: '58',
    name: 'AssemblyAI',
    description: 'AI models for speech-to-text, speech understanding, and more, via API.',
    longDescription: 'AssemblyAI offers a suite of powerful AI models for developers to transcribe and understand audio and video data, including features like summarization, content moderation, and topic detection.',
    category: 'Audio',
    website: 'https://www.assemblyai.com',
    imageUrl: `/ai-tools/${createSlug('AssemblyAI')}.png`,
    imageKeywords: 'AssemblyAI API',
    rating: 4.7,
    tags: ['speech-to-text api', 'audio intelligence', 'developer tool'],
    pricing: 'Paid',
    features: ['Accurate speech-to-text', 'Audio summarization', 'PII redaction', 'Topic detection', 'Sentiment analysis'],
  },
  {
    id: '59',
    name: 'LALAL.AI',
    description: 'AI-powered stem splitter for extracting vocals, accompaniment, and instruments from any audio.',
    longDescription: 'LALAL.AI uses advanced AI to quickly and accurately separate audio tracks into stems, allowing users to extract vocals, drums, bass, piano, and other instruments from songs or videos.',
    category: 'Audio',
    website: 'https://www.lalal.ai',
    imageUrl: `/ai-tools/${createSlug('LALAL.AI')}.png`,
    imageKeywords: 'LALALAI stems',
    rating: 4.5,
    tags: ['stem separation', 'vocal remover', 'music tool'],
    pricing: 'Freemium',
    features: ['High-quality stem splitting', 'Supports various instruments', 'Fast processing', 'API available'],
  },
  {
    id: '60',
    name: 'Resemble.ai',
    description: 'Complete generative voice AI toolkit for creating realistic human-like voiceovers.',
    longDescription: 'Resemble.ai provides tools for voice cloning, custom AI voice generation, real-time speech-to-speech, and neural audio editing, catering to game developers, filmmakers, and enterprises.',
    category: 'Audio',
    website: 'https://www.resemble.ai',
    imageUrl: `/ai-tools/${createSlug('Resemble.ai')}.png`,
    imageKeywords: 'ResembleAI voice',
    rating: 4.4,
    tags: ['voice cloning', 'generative voice', 'speech-to-speech'],
    pricing: 'Paid',
    features: ['Rapid voice cloning', 'Speech-to-speech transformation', 'Emotion control', 'Localization tools', 'API access'],
  },
  {
    id: '61',
    name: 'Microsoft 365 Copilot',
    description: 'AI assistant integrated across Microsoft 365 apps like Word, Excel, PowerPoint, Outlook, and Teams.',
    longDescription: 'Microsoft 365 Copilot combines the power of large language models with your data in the Microsoft Graph and Microsoft 365 apps to help you create, summarize, analyze, and collaborate more effectively.',
    category: 'Productivity',
    website: 'https://www.microsoft.com/en-us/microsoft-365/copilot-for-microsoft-365',
    imageUrl: `/ai-tools/${createSlug('Microsoft 365 Copilot')}.png`,
    imageKeywords: 'Microsoft Copilot',
    rating: 4.7,
    tags: ['microsoft office', 'ai assistant', 'enterprise productivity'],
    pricing: 'Paid',
    features: ['Integrated into M365 apps', 'Works with your business data', 'Draft documents, emails, presentations', 'Summarize meetings'],
  },
  {
    id: '62',
    name: 'Gamma.app',
    description: 'AI-powered alternative to slide decks for creating engaging presentations quickly.',
    longDescription: 'Gamma helps you create beautiful and interactive presentations, documents, or webpages using AI. Just start writing, and Gamma will handle the formatting and design.',
    category: 'Productivity',
    website: 'https://gamma.app',
    imageUrl: `/ai-tools/${createSlug('Gamma.app')}.png`,
    imageKeywords: 'Gamma app',
    rating: 4.6,
    tags: ['presentations', 'ai slides', 'content creation'],
    pricing: 'Freemium',
    features: ['AI-generated presentations from prompts', 'Interactive content blocks', 'Responsive design', 'Easy sharing'],
  },
  {
    id: '63',
    name: 'Tome',
    description: 'AI-powered storytelling format for creating presentations, pitches, and more.',
    longDescription: 'Tome is a generative storytelling tool that helps users create compelling narratives and presentations by generating entire outlines, pages, text, and images based on a prompt.',
    category: 'Productivity',
    website: 'https://tome.app',
    imageUrl: `/ai-tools/${createSlug('Tome')}.png`,
    imageKeywords: 'Tome presentation',
    rating: 4.5,
    tags: ['storytelling', 'ai presentations', 'visual content'],
    pricing: 'Freemium',
    features: ['Generative text and images', 'Interactive embeds', 'Responsive layouts', 'Collaboration features'],
  },
  {
    id: '64',
    name: 'ClickUp AI',
    description: 'AI assistant integrated into the ClickUp project management platform.',
    longDescription: 'ClickUp AI brings artificial intelligence into your project management workflow, helping with tasks like summarizing documents, writing updates, generating ideas, and automating repetitive work.',
    category: 'Productivity',
    website: 'https://clickup.com/ai',
    imageUrl: `/ai-tools/${createSlug('ClickUp AI')}.png`,
    imageKeywords: 'ClickUp AI',
    rating: 4.4,
    tags: ['project management', 'ai assistant', 'task automation'],
    pricing: 'Paid',
    features: ['Summarize tasks and documents', 'Generate action items', 'Write content and emails', 'Automate workflows'],
  },
  {
    id: '65',
    name: 'Asana Intelligence',
    description: 'AI features within Asana to enhance project management and team productivity.',
    longDescription: 'Asana Intelligence uses AI to help teams manage projects more effectively by providing smart summaries, goal setting assistance, workflow automation, and personalized insights.',
    category: 'Productivity',
    website: 'https://asana.com/ai',
    imageUrl: `/ai-tools/${createSlug('Asana Intelligence')}.png`,
    imageKeywords: 'Asana AI',
    rating: 4.3,
    tags: ['asana', 'project management ai', 'team collaboration'],
    pricing: 'Paid',
    features: ['Smart summaries', 'AI-assisted goal setting', 'Workflow automation suggestions', 'Personalized work insights'],
  },
  {
    id: '66',
    name: 'Motion',
    description: 'AI-powered calendar and project management tool to optimize your time.',
    longDescription: 'Motion uses AI to automatically schedule tasks, meetings, and projects into your calendar, helping you manage your time effectively and ensure deadlines are met.',
    category: 'Productivity',
    website: 'https://www.usemotion.com',
    imageUrl: `/ai-tools/${createSlug('Motion')}.png`,
    imageKeywords: 'Motion calendar',
    rating: 4.5,
    tags: ['ai calendar', 'task scheduling', 'time management'],
    pricing: 'Paid',
    features: ['Automated task scheduling', 'AI meeting assistant', 'Project planning', 'Calendar optimization'],
  },
  {
    id: '67',
    name: 'Fireflies.ai',
    description: 'AI meeting assistant that transcribes, summarizes, and analyzes voice conversations.',
    longDescription: 'Fireflies.ai joins your meetings to record, transcribe, and summarize them. It also allows you to search across past conversations and identify key action items and topics.',
    category: 'Productivity',
    website: 'https://fireflies.ai',
    imageUrl: `/ai-tools/${createSlug('Fireflies.ai')}.png`,
    imageKeywords: 'Fireflies meeting',
    rating: 4.6,
    tags: ['meeting transcription', 'ai summary', 'conversation intelligence'],
    pricing: 'Freemium',
    features: ['Automated transcription', 'AI-powered summaries', 'Action item detection', 'Integrates with popular conferencing tools'],
  },
  {
    id: '68',
    name: 'SaneBox',
    description: 'AI-powered email management tool that prioritizes important emails and declutters your inbox.',
    longDescription: 'SaneBox uses AI algorithms to learn your email habits and automatically filters unimportant emails out of your inbox into a separate folder, helping you focus on what matters.',
    category: 'Productivity',
    website: 'https://www.sanebox.com',
    imageUrl: `/ai-tools/${createSlug('SaneBox')}.png`,
    imageKeywords: 'SaneBox email',
    rating: 4.4,
    tags: ['email management', 'inbox zero', 'ai filter'],
    pricing: 'Paid',
    features: ['AI email filtering', 'Do Not Disturb mode', 'Attachment reminders', 'Unsubscribe from unwanted emails'],
  },
  {
    id: '69',
    name: 'Todoist AI Assistant',
    description: 'AI features integrated into Todoist to help manage tasks and projects.',
    longDescription: 'Todoist AI Assistant helps users break down tasks, suggest next steps, and achieve their goals more efficiently by integrating AI capabilities into the task management workflow.',
    category: 'Productivity',
    website: 'https://todoist.com/features/ai-assistant',
    imageUrl: `/ai-tools/${createSlug('Todoist AI Assistant')}.png`,
    imageKeywords: 'Todoist AI',
    rating: 4.3,
    tags: ['task management', 'todo list', 'ai planner'],
    pricing: 'Freemium',
    features: ['Task breakdown suggestions', 'Goal achievement assistance', 'Natural language task creation'],
  },
  {
    id: '70',
    name: 'Mem X',
    description: 'AI-powered self-organizing workspace that helps you capture, connect, and share information.',
    longDescription: 'Mem X uses AI to automatically organize your notes, documents, and ideas, making it easier to find information and discover connections you might have missed. It features smart search and summarization.',
    category: 'Productivity',
    website: 'https://mem.ai',
    imageUrl: `/ai-tools/${createSlug('Mem X')}.png`,
    imageKeywords: 'Mem X',
    rating: 4.5,
    tags: ['knowledge management', 'note-taking', 'ai workspace'],
    pricing: 'Freemium',
    features: ['AI-powered organization', 'Smart search and summarization', 'Collaborative features', 'Calendar integration'],
  },
  {
    id: '71',
    name: 'Uizard',
    description: 'AI-powered UI design tool for creating wireframes, mockups, and prototypes from text or sketches.',
    longDescription: 'Uizard allows users to generate editable UI designs from text prompts, hand-drawn sketches, or screenshots, significantly speeding up the wireframing and prototyping process.',
    category: 'Design',
    website: 'https://uizard.io',
    imageUrl: `/ai-tools/${createSlug('Uizard')}.png`,
    imageKeywords: 'Uizard UI',
    rating: 4.5,
    tags: ['ui design', 'wireframing', 'prototyping', 'sketch-to-design'],
    pricing: 'Freemium',
    features: ['Text-to-UI generation', 'Sketch-to-UI conversion', 'Theme generation', 'Collaboration tools'],
  },
  {
    id: '72',
    name: 'Khroma',
    description: 'AI color palette generator that learns your aesthetic preferences.',
    longDescription: 'Khroma uses AI to learn which colors you like and generates an unlimited number of color palettes for your design projects, helping you discover and save color combinations.',
    category: 'Design',
    website: 'https://khroma.co',
    imageUrl: `/ai-tools/${createSlug('Khroma')}.png`,
    imageKeywords: 'Khroma color',
    rating: 4.3,
    tags: ['color palette', 'ai design tool', 'color theory'],
    pricing: 'Free',
    features: ['Personalized color palette generation', 'Search by color value or keyword', 'Filter by hue, saturation, brightness'],
  },
  {
    id: '73',
    name: 'Looka',
    description: 'AI-powered platform for designing a logo and building a brand.',
    longDescription: 'Looka uses AI to help you create a custom logo and establish your brand identity. It also offers tools for creating websites, business cards, and social media assets based on your logo design.',
    category: 'Design',
    website: 'https://looka.com',
    imageUrl: `/ai-tools/${createSlug('Looka')}.png`,
    imageKeywords: 'Looka logo',
    rating: 4.4,
    tags: ['logo design', 'branding', 'ai graphic design'],
    pricing: 'Paid',
    features: ['AI logo generation', 'Brand kit creation', 'Website builder', 'Social media templates'],
  },
  {
    id: '74',
    name: 'Autodraw',
    description: 'A fast drawing tool by Google that pairs machine learning with drawings from talented artists.',
    longDescription: 'Autodraw is a drawing tool that uses AI to guess what you\'re trying to draw and replaces your doodle with a polished illustration from a library of artist-created drawings.',
    category: 'Design',
    website: 'https://www.autodraw.com',
    imageUrl: `/ai-tools/${createSlug('Autodraw')}.png`,
    imageKeywords: 'Autodraw Google',
    rating: 4.2,
    tags: ['drawing tool', 'google ai', 'illustration aid'],
    pricing: 'Free',
    features: ['AI-powered drawing suggestions', 'Simple interface', 'Free to use', 'Works on any device'],
  },
  {
    id: '75',
    name: 'Designs.ai',
    description: 'Online suite of AI-powered creative tools for logos, videos, banners, and mockups.',
    longDescription: 'Designs.ai provides an all-in-one platform with AI tools to create logos, videos, banners, voiceovers, and mockups quickly and easily, aimed at marketers and small businesses.',
    category: 'Design',
    website: 'https://designs.ai',
    imageUrl: `/ai-tools/${createSlug('Designs.ai')}.png`,
    imageKeywords: 'DesignsAI suite',
    rating: 4.3,
    tags: ['creative suite', 'ai design', 'marketing assets'],
    pricing: 'Freemium',
    features: ['Logomaker', 'Videomaker', 'Designmaker (banners)', 'Speechmaker (voiceover)', 'Mockupmaker'],
  },
  {
    id: '76',
    name: 'Let\'s Enhance',
    description: 'AI image upscaler and enhancer to improve image quality and resolution.',
    longDescription: 'Let\'s Enhance uses AI algorithms to increase image resolution without losing quality, remove noise, and improve colors and lighting in photos.',
    category: 'Design',
    website: 'https://letsenhance.io',
    imageUrl: `/ai-tools/${createSlug('Let\'s Enhance')}.png`,
    imageKeywords: 'LetsEnhance upscale',
    rating: 4.4,
    tags: ['image upscaling', 'photo enhancement', 'resolution increase'],
    pricing: 'Freemium',
    features: ['Upscale images up to 16x', 'Color and tone enhancement', 'Noise reduction', 'Batch processing'],
  },
  {
    id: '77',
    name: 'remove.bg',
    description: 'Automatically remove image backgrounds in 5 seconds with zero clicks.',
    longDescription: 'remove.bg is a popular tool that uses AI to instantly remove the background from any image, providing a transparent background or allowing users to add a new one.',
    category: 'Design',
    website: 'https://www.remove.bg',
    imageUrl: `/ai-tools/${createSlug('remove.bg')}.png`,
    imageKeywords: 'removebg background',
    rating: 4.6,
    tags: ['background removal', 'photo editing', 'quick tool'],
    pricing: 'Freemium',
    features: ['Automatic background removal', 'High precision', 'Plugin for design tools', 'API access'],
  },
  {
    id: '78',
    name: 'Beautiful.ai',
    description: 'AI presentation software that designs your slides for you.',
    longDescription: 'Beautiful.ai uses AI to apply design best practices to your presentations, ensuring they look professional and consistent. It automates layout, formatting, and visual choices.',
    category: 'Design',
    website: 'https://www.beautiful.ai',
    imageUrl: `/ai-tools/${createSlug('Beautiful.ai')}.png`,
    imageKeywords: 'BeautifulAI slides',
    rating: 4.5,
    tags: ['presentation design', 'ai slides', 'automated design'],
    pricing: 'Paid',
    features: ['Smart templates', 'Automated slide formatting', 'Branding consistency', 'Collaboration tools'],
  },
  {
    id: '79',
    name: 'Genius by Diagram',
    description: 'AI design companion that automates design tasks and generates UI ideas.',
    longDescription: 'Genius, from Diagram (acq. by Figma), is an AI tool intended to assist designers with UI generation, design system automation, and exploring design variations quickly.',
    category: 'Design',
    website: 'https://diagram.com',
    imageUrl: `/ai-tools/${createSlug('Genius by Diagram')}.png`,
    imageKeywords: 'Diagram Genius',
    rating: 4.4,
    tags: ['ui generation', 'design automation', 'figma plugin'],
    pricing: 'Contact for Pricing',
    features: ['AI UI generation', 'Design system integration', 'Automates design tasks', 'Explores variations'],
  },
  {
    id: '80',
    name: 'Visily',
    description: 'AI-powered UI design and wireframing tool for fast mockups and prototypes.',
    longDescription: 'Visily helps teams create app mockups and prototypes rapidly using AI. It offers features like screenshot-to-design, AI-generated templates, and collaborative editing.',
    category: 'Design',
    website: 'https://www.visily.ai',
    imageUrl: `/ai-tools/${createSlug('Visily')}.png`,
    imageKeywords: 'Visily wireframe',
    rating: 4.3,
    tags: ['ai wireframing', 'mockup tool', 'ui design software'],
    pricing: 'Freemium',
    features: ['Screenshot to design', 'AI-generated templates', 'Component library', 'Collaboration', 'Prototyping'],
  },
  {
    id: '81',
    name: 'Character.ai',
    description: 'Platform for creating and interacting with AI-powered chatbots with distinct personalities.',
    longDescription: 'Character.ai allows users to create and chat with AI characters based on fictional figures, historical personalities, or original creations, offering a unique conversational experience.',
    category: 'Other',
    website: 'https://character.ai',
    imageUrl: `/ai-tools/${createSlug('Character.ai')}.png`,
    imageKeywords: 'CharacterAI chatbot',
    rating: 4.5,
    tags: ['chatbot', 'ai characters', 'conversational ai'],
    pricing: 'Freemium',
    features: ['Create custom AI characters', 'Chat with various personalities', 'Community-created characters', 'Role-playing'],
  },
  {
    id: '82',
    name: 'Replika',
    description: 'AI companion who cares. Always here to listen and talk. Always on your side.',
    longDescription: 'Replika is an AI chatbot designed to be a personal companion, offering emotional support, conversation, and a space for users to express themselves freely.',
    category: 'Other',
    website: 'https://replika.com',
    imageUrl: `/ai-tools/${createSlug('Replika')}.png`,
    imageKeywords: 'Replika companion',
    rating: 4.2,
    tags: ['ai companion', 'chatbot', 'mental well-being'],
    pricing: 'Freemium',
    features: ['Personalized conversations', 'Mood tracking', 'Activities and coaching', 'Augmented Reality (AR) mode'],
  },
  {
    id: '83',
    name: 'Rose AI',
    description: 'AI research platform for finding, visualizing, and sharing data.',
    longDescription: 'Rose AI helps users quickly find, clean, visualize, and share data from various sources, using AI to streamline the research and analysis process for financial and economic data.',
    category: 'Other',
    website: 'https://rose.ai',
    imageUrl: `/ai-tools/${createSlug('Rose AI')}.png`,
    imageKeywords: 'RoseAI data',
    rating: 4.3,
    tags: ['data research', 'ai analysis', 'visualization'],
    pricing: 'Paid',
    features: ['AI-powered data search', 'Data cleaning and transformation', 'Visualization tools', 'Collaboration on datasets'],
  },
  {
    id: '84',
    name: 'Elicit',
    description: 'AI research assistant to automate research workflows, like literature reviews.',
    longDescription: 'Elicit uses language models to help automate parts of the research process, such as finding relevant papers, summarizing them, and extracting key information for literature reviews.',
    category: 'Other',
    website: 'https://elicit.org',
    imageUrl: `/ai-tools/${createSlug('Elicit')}.png`,
    imageKeywords: 'Elicit research',
    rating: 4.6,
    tags: ['research assistant', 'literature review', 'academic ai'],
    pricing: 'Free',
    features: ['Find relevant papers', 'Summarize research papers', 'Extract information', 'Brainstorm research questions'],
  },
  {
    id: '85',
    name: 'Consensus',
    description: 'AI search engine for research, extracting and synthesizing findings from scientific papers.',
    longDescription: 'Consensus is an AI-powered search engine that directly answers questions by finding and summarizing results from published scientific research, providing evidence-based insights.',
    category: 'Other',
    website: 'https://consensus.app',
    imageUrl: `/ai-tools/${createSlug('Consensus')}.png`,
    imageKeywords: 'Consensus search',
    rating: 4.5,
    tags: ['scientific research', 'ai search', 'evidence-based answers'],
    pricing: 'Freemium',
    features: ['Search scientific papers', 'Get summarized answers with citations', 'Analyze study rigor', 'Topic-specific feeds'],
  },
  {
    id: '86',
    name: 'LegalRobot',
    description: 'AI platform for understanding and creating legal documents.',
    longDescription: 'LegalRobot uses AI to analyze legal documents, identify potential issues, and help users understand complex legal language. It also offers tools for generating common legal agreements.',
    category: 'Other',
    website: 'https://legalrobot.com',
    imageUrl: `/ai-tools/${createSlug('LegalRobot')}.png`,
    imageKeywords: 'LegalRobot document',
    rating: 4.1,
    tags: ['legal tech', 'document analysis', 'ai law'],
    pricing: 'Freemium',
    features: ['Legal document analysis', 'Plain language summaries', 'Template generation', 'Clause library'],
  },
  {
    id: '87',
    name: 'Paige',
    description: 'AI-powered digital pathology for cancer diagnosis and treatment.',
    longDescription: 'Paige develops AI-based software for pathologists to improve the speed and accuracy of cancer diagnosis by analyzing digital pathology slides.',
    category: 'Other',
    website: 'https://paige.ai',
    imageUrl: `/ai-tools/${createSlug('Paige')}.png`,
    imageKeywords: 'Paige pathology',
    rating: 4.7,
    tags: ['healthcare ai', 'pathology', 'cancer diagnosis'],
    pricing: 'Contact for Pricing',
    features: ['AI-assisted cancer detection', 'Workflow enhancement for pathologists', 'FDA-cleared products', 'Biomarker discovery'],
  },
  {
    id: '88',
    name: 'PolyAI',
    description: 'Developer of enterprise-grade voice assistants for customer service.',
    longDescription: 'PolyAI creates highly conversational AI voice assistants for businesses to automate customer service calls, providing human-like interactions and resolving complex queries.',
    category: 'Other',
    website: 'https://poly.ai',
    imageUrl: `/ai-tools/${createSlug('PolyAI')}.png`,
    imageKeywords: 'PolyAI voice',
    rating: 4.4,
    tags: ['enterprise ai', 'voice assistant', 'customer service'],
    pricing: 'Contact for Pricing',
    features: ['Conversational AI for voice', 'Multilingual support', 'Integration with contact center platforms', 'Customizable workflows'],
  },
  {
    id: '89',
    name: 'DataRobot',
    description: 'Enterprise AI platform for building, deploying, and managing machine learning models.',
    longDescription: 'DataRobot provides an end-to-end platform for automated machine learning (AutoML), enabling organizations to quickly build and deploy AI applications at scale.',
    category: 'Other',
    website: 'https://www.datarobot.com',
    imageUrl: `/ai-tools/${createSlug('DataRobot')}.png`,
    imageKeywords: 'DataRobot AutoML',
    rating: 4.6,
    tags: ['automl', 'machine learning', 'enterprise ai platform'],
    pricing: 'Paid',
    features: ['Automated model building', 'MLOps capabilities', 'Time series forecasting', 'Explainable AI'],
  },
  {
    id: '90',
    name: 'H2O.ai',
    description: 'Open source leader in AI and ML, providing a comprehensive AI Cloud platform.',
    longDescription: 'H2O.ai offers an AI Cloud platform with open-source and enterprise solutions for building, deploying, and managing machine learning models and AI applications across various industries.',
    category: 'Other',
    website: 'https://h2o.ai',
    imageUrl: `/ai-tools/${createSlug('H2O.ai')}.png`,
    imageKeywords: 'H2OAI cloud',
    rating: 4.5,
    tags: ['open source ai', 'ai cloud', 'machine learning platform'],
    pricing: 'Freemium',
    features: ['Open source libraries (H2O-3, Sparkling Water)', 'Driverless AI (AutoML)', 'AI AppStore', 'Industry-specific solutions'],
  },
  {
    id: '91',
    name: 'VEO3',
    description: 'Google\'s most capable generative video model, creating high-quality, realistic videos from text prompts.',
    longDescription: 'VEO3 is Google\'s state-of-the-art model for generating high-definition video from text, image, and video prompts. It showcases a deep understanding of natural language and visual semantics, enabling it to create coherent and cinematic shots over extended durations.',
    category: 'Video',
    website: 'https://deepmind.google/technologies/veo/',
    imageUrl: `/ai-tools/veo3.png`,
    imageKeywords: 'google veo',
    rating: 4.9,
    tags: ['text-to-video', 'google deepmind', 'generative video', 'high definition'],
    pricing: 'Contact for Pricing',
  },
  {
    id: '92',
    name: 'BOLT',
    description: 'An ultra-fast AI-powered workflow engine for automating complex business processes and data pipelines.',
    longDescription: 'BOLT is a next-generation automation platform that leverages AI to execute workflows with unparalleled speed and efficiency. It is designed for high-throughput data processing and real-time process automation in enterprise environments.',
    category: 'Productivity',
    website: '#',
    imageUrl: `/ai-tools/bolt.png`,
    imageKeywords: 'bolt automation',
    rating: 4.5,
    tags: ['workflow automation', 'data processing', 'speed', 'enterprise'],
    pricing: 'Paid',
    features: ['High-speed execution', 'AI-assisted workflow design', 'Scalable architecture', 'Real-time monitoring'],
    isSponsored: true,
  },
  {
    id: '93',
    name: 'n8n',
    description: 'Open-source workflow automation tool to connect services and build complex automations with or without code.',
    longDescription: 'n8n is a fair-code licensed and self-hostable workflow automation tool. It enables you to connect various web services and APIs to create powerful, customized workflows without needing extensive programming knowledge.',
    category: 'Productivity',
    website: 'https://n8n.io/',
    imageUrl: `/ai-tools/n8n.png`,
    imageKeywords: 'n8n workflow',
    rating: 4.7,
    tags: ['workflow automation', 'open source', 'low-code', 'api integration', 'self-hostable'],
    pricing: 'Freemium',
    features: ['Over 350 native integrations', 'Custom node creation', 'Self-hosting option', 'Fair-code license'],
  }
];
