
import type { AiTool, AiToolCategory } from '@/types';

export const aiToolCategories: AiToolCategory[] = [
  'LLM',
  'Photo',
  'Video',
  'Coding',
  'Audio',
  'Productivity',
  'Design',
  'Other',
];

export const aiTools: AiTool[] = [
  {
    id: '1',
    name: 'GPT-4 Turbo',
    description: 'Advanced large language model for text generation and understanding.',
    longDescription: 'GPT-4 Turbo by OpenAI is a state-of-the-art language model with a larger context window and more up-to-date knowledge, excelling in complex reasoning, coding, and creative text generation.',
    category: 'LLM',
    website: 'https://openai.com/gpt-4',
    imageUrl: 'https://placehold.co/600x400.png',
    rating: 4.9,
    tags: ['text generation', 'nlp', 'coding assistant'],
    pricing: 'Paid',
    features: ['128k context window', 'Vision capabilities', 'Advanced reasoning'],
  },
  {
    id: '2',
    name: 'Midjourney',
    description: 'AI image generator creating stunning visuals from text prompts.',
    longDescription: 'Midjourney is an independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species. It generates images from textual descriptions, known as "prompts".',
    category: 'Photo',
    website: 'https://www.midjourney.com',
    imageUrl: 'https://placehold.co/600x400.png',
    rating: 4.8,
    tags: ['image generation', 'art', 'design'],
    pricing: 'Paid',
    features: ['High-quality artistic images', 'Discord-based interface', 'Community showcase'],
  },
  {
    id: '3',
    name: 'Runway Gen-2',
    description: 'Generate novel videos with text, images or video clips.',
    longDescription: 'Runway Gen-2 is a multimodal AI system that can generate novel videos with text, images or video clips. It allows users to create video content in various styles and moods.',
    category: 'Video',
    website: 'https://runwayml.com',
    imageUrl: 'https://placehold.co/600x400.png',
    rating: 4.7,
    tags: ['video generation', 'text-to-video', 'creative tool'],
    pricing: 'Freemium',
    features: ['Text-to-video', 'Image-to-video', 'Video stylization', 'Inpainting'],
  },
  {
    id: '4',
    name: 'GitHub Copilot',
    description: 'AI pair programmer that helps you write code faster.',
    longDescription: 'GitHub Copilot is an AI pair programmer that offers autocomplete-style suggestions as you code. You can get suggestions from GitHub Copilot either by starting to write the code you want to use, or by writing a natural language comment describing what you want the code to do.',
    category: 'Coding',
    website: 'https://copilot.github.com',
    imageUrl: 'https://placehold.co/600x400.png',
    rating: 4.6,
    tags: ['code assistant', 'developer tool', 'ide plugin'],
    pricing: 'Paid',
    features: ['Code suggestions', 'Natural language to code', 'Supports multiple languages', 'IDE integration'],
  },
  {
    id: '5',
    name: 'Descript',
    description: 'All-in-one audio and video editing, as easy as a doc.',
    longDescription: 'Descript is an AI-powered audio and video editing tool that transcribes audio to text, allowing users to edit media by editing the text. It offers features like overdub, screen recording, and podcasting tools.',
    category: 'Audio',
    website: 'https://www.descript.com',
    imageUrl: 'https://placehold.co/600x400.png',
    rating: 4.5,
    tags: ['audio editing', 'video editing', 'transcription', 'podcasting'],
    pricing: 'Freemium',
    features: ['AI transcription', 'Overdub (voice cloning)', 'Screen recording', 'Podcast production tools'],
  },
  {
    id: '6',
    name: 'Notion AI',
    description: 'AI-powered assistant integrated into your Notion workspace.',
    longDescription: 'Notion AI helps you work faster, write better, and think bigger, right in your Notion workspace. It can summarize documents, draft emails, translate text, and more.',
    category: 'Productivity',
    website: 'https://www.notion.so/ai',
    imageUrl: 'https://placehold.co/600x400.png',
    rating: 4.4,
    tags: ['writing assistant', 'summarization', 'workspace tool'],
    pricing: 'Freemium',
    features: ['Text generation & editing', 'Summarization', 'Action items extraction', 'Translation'],
  },
  {
    id: '7',
    name: 'Figma AI',
    description: 'AI tools to supercharge your design workflow in Figma.',
    longDescription: 'Figma AI integrates generative AI capabilities directly into the Figma design platform, helping designers automate tasks, generate design ideas, and iterate faster.',
    category: 'Design',
    website: 'https://www.figma.com/ai',
    imageUrl: 'https://placehold.co/600x400.png',
    rating: 4.3,
    tags: ['design tool', 'ui/ux', 'prototyping'],
    pricing: 'Paid',
    features: ['Generative design', 'Automated layout suggestions', 'Content generation for mockups'],
  },
  {
    id: '8',
    name: 'Claude 3',
    description: 'A family of foundation models for various text-based tasks.',
    longDescription: 'Claude 3 by Anthropic offers a new generation of AI models (Haiku, Sonnet, Opus) that balance intelligence, speed, and cost, suitable for a wide range of applications from quick summarization to complex analysis.',
    category: 'LLM',
    website: 'https://www.anthropic.com/claude',
    imageUrl: 'https://placehold.co/600x400.png',
    rating: 4.8,
    tags: ['llm', 'text analysis', 'chatbot'],
    pricing: 'Freemium',
    features: ['Multiple model sizes', 'Strong safety features', 'Long context processing'],
  },
  {
    id: '9',
    name: 'Adobe Firefly',
    description: 'Generative AI for creative expression integrated into Adobe products.',
    longDescription: 'Adobe Firefly is a family of creative generative AI models coming to Adobe products. It focuses on generating images and text effects designed to be safe for commercial use.',
    category: 'Photo',
    website: 'https://www.adobe.com/sensei/generative-ai/firefly.html',
    imageUrl: 'https://placehold.co/600x400.png',
    rating: 4.7,
    tags: ['image generation', 'text effects', 'adobe suite'],
    pricing: 'Freemium',
    features: ['Ethically sourced training data', 'Integration with Photoshop, Illustrator', 'Text-to-image', 'Generative fill'],
  },
  {
    id: '10',
    name: 'Synthesia',
    description: 'Create AI videos by typing in text. No actors, cameras or mics needed.',
    longDescription: 'Synthesia is an AI video generation platform that allows users to create professional-looking videos with AI avatars and voiceovers in multiple languages, simply by typing text.',
    category: 'Video',
    website: 'https://www.synthesia.io',
    imageUrl: 'https://placehold.co/600x400.png',
    rating: 4.6,
    tags: ['ai video', 'avatar', 'text-to-speech'],
    pricing: 'Paid',
    features: ['AI avatars', 'Multi-language support', 'Customizable templates', 'Screen recording'],
  },
  // Add more tools to reach 50. This is a sample.
];
